---
title: "EDA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(lubridate)
library(dplyr)
library(ggplot2)


#Read in excel file
ibs_dat <- read_excel("~/Desktop/RL_IBS/ibs_dat.xlsx", skip = 1)
```


```{r}
## dimensions-- 500 total claims
dim(ibs_dat)

## unique date in year-month-date-- 88 unique dates
length(unique(ibs_dat$from_dt))

## unique claim codes-- 155 
length(unique(ibs_dat$claimno))

## unique procedure descriptions-- 142
length(unique(ibs_dat$PROCEDURE_DESC))
```

```{r}
#sort from least recent to most recent
#ibs_dat %>% arrange(ymd(ibs_dat$from_dt))

## The database does not consistently capture drug therapy administered during an inpatient confinement. This is based on how the treatments are billed. we may receive only revenue codes indicating drugs were administered. 
```

```{r}
## First group by date, then tally the number of claims for each date

######## Question to ask: are we more interested in looking at the unique claims? What does it mean for two entries to have the same claim number on the same treatment day?


### unique claims & counts per date
unique_claim_counts <- ibs_dat %>% arrange(ymd(ibs_dat$from_dt)) %>%
                 group_by(from_dt, claimno) %>%
                 tally

## Create plot with unique "from_dt" as x-axis, number of TOTAL claims as y-axis
########## This graph isn't that helpful and needs to be broken down 
ggplot(data = unique_claim_counts, aes(x = from_dt, y = n)) +
      geom_bar(stat = "identity", fill = "purple") +
      labs(title ="Total Number of Claims (non-unique) per visit date",
           x = "Date", y = "Number of (non-unique) Claims")

## Plot with date on y axis, number of unique visits per YEAR-- isolate distinct from_dt and count 
### However, this visualization will count a single hospitalization as multiple visits since those are over multiple days
## Question   1. 

unique_visits_year <- ibs_dat %>% distinct(from_dt, .keep_all = TRUE) %>% mutate(month = format(from_dt, "%m"),
                                                           year = format(from_dt, "%Y")) %>% group_by(year) %>% tally

ggplot(data = unique_visits_year, aes(x = year, y = n, group = 1)) +
      geom_point() + geom_line(linetype=2) +
      labs(title ="Total Number of Unique Visits per Year",
           x = "Year", y = "Number of Visits")

## We can also group these by month from year to year
unique_visits_month <- ibs_dat %>% distinct(from_dt, .keep_all = TRUE) %>% mutate(month = format(from_dt, "%m"),
                                                           year = format(from_dt, "%Y")) %>% group_by(year, month) %>% tally


ggplot(data = unique_visits_month, aes(x = month, y = n, group = 1)) +
      facet_wrap(~year) + geom_point() + geom_line(linetype=2) +
      labs(title ="Unique Visits Each Month by Year",
           x = "Year", y = "Number of Visits")


### This doesn't seem to be that informative either. We can see an increasing trend in visits in 2012, also bunch in July of 2011-- maybe these are hospitalizations? 
### From the code below we can see that IS the case. There were only 3 unique hospitalizations, all in 2011 

ibs_dat[!is.na(ibs_dat[,"conf_num"]),] %>% distinct(from_dt, .keep_all = TRUE) %>% mutate(month = format(from_dt, "%m"),
                                                           year = format(from_dt, "%Y")) %>% group_by(year, month, conf_num) %>% tally
```

Build a timeline for hospitalizations-- count number of hospitalizations throughout time frame
```{r}
### count number of hospitalizations throughout time frame
#All of the claims with the same patient ID and confinement number belong to the same unique inpatient stay-- unique hospitalizations

### 3 unique hospitalizations for THIS specific patient 
unique(ibs_dat$conf_num)

### visualize hospitalizations, get count of claims per date per unique hospitalization by year & month
hosp_time <- ibs_dat %>% distinct(from_dt, .keep_all = TRUE) %>% mutate(month = format(from_dt, "%m"),
                                                           year = format(from_dt, "%Y")) %>%
                 group_by(conf_num, year, month) %>%
                 tally()
 
ggplot(data = hosp_time[hosp_time$year == 2011, ], aes(x = month, y = n, fill = conf_num)) + geom_bar(stat='identity') +
      labs(title ="Unique Visits by Month in 2011",
           x = "Year", y = "Unique visits per month")


### count length of hospitalization throughout time frame 
##### Flawed approac-- actually need to look at first & last day

ibs_dat %>% group_by(conf_num) %>% summarise(distinct_days = n_distinct(from_dt))

length(unique(ibs_dat$from_dt))
```

Starting to group together bloodwork, imaging, surgery, colonoscopy, prescription claims
```{r}
events_timeline_procedure <- ibs_dat %>% 
  # IBS-- need to include this separately because of possibility of overwriting
  #mutate(event_type = ifelse(Primary_diag == "Irritable Bowel Syndrome", "IBS_diagnosis", NA)) %>%
  
  ### Create event_type as column of NAs
  mutate(event_type = NA) %>%
  
  mutate(event_type = case_when(
    grepl("emergency department", PROCEDURE_DESC, ignore.case = TRUE) ~ "ED_visit",
    grepl("colonoscopy", PROCEDURE_DESC, ignore.case = TRUE) ~ "colonoscopy",
    grepl("Esophagogastroduodenoscopy", 
          PROCEDURE_DESC, ignore.case = TRUE) ~ "esophagogastroduodenoscopy",
    (grepl("Enterectomy", PROCEDURE_DESC, ignore.case = TRUE) | 
       grepl("Enterostomy", PROCEDURE_DESC, ignore.case = TRUE)) ~ "surgery",
    (grepl("ultrasound", PROCEDURE_DESC, ignore.case = TRUE) | 
       grepl("tomography", PROCEDURE_DESC, ignore.case = TRUE) ~ "imaging")))

```

Want to group data within 3 day intervals to categorize that as one visit
```{r}
#so all the points that are 3 days or less apart are put into one group
## want to exclude hospitalizations bc those are a single visit (if conf_num exists = hospitalization)
```


Create new column for labs & imaging
```{r}
library(dplyr)
library(ggplot2)
library(lubridate)

ibs_dat$lab <- 0
ibs_dat$imaging <- 0

ibs_lab_image <- ibs_dat %>%
  
  ## group the labs
  mutate(lab = case_when(
    ## CBC w/ diff
    proc_cde ==  "85025" ~ "cbc_w_diff",
    
      ## C reactive protein
    proc_cde == "86140" ~ "c_reactive_protein",  
      
    ## Erythrocyte sedimentation rate
    proc_cde == "85651" | 
    proc_cde == "85652" ~ "erythrocyte_sed_rate",
    
    ## Albumin
    proc_cde == "82040" ~ "albumin",
    
    ## AST
    proc_cde == "84450" ~ "ast", 
    
    ## ALT
    proc_cde == "84460" ~ "alt", 
    
    ## Total protein
    proc_cde == "84155" ~"total_protein")) %>%


  mutate(imaging = case_when(
    
    ## CT abdomen w/ & w/o contrast
    proc_cde == "74170" ~ "ct_abdomen_w_wo_contrast",
    
    ## CT abdomen & pelvis w/o contrast
    proc_cde == "74176"  ~ "ct_abdomen_pelvis_wo_contrast",
    
    ## CT abdomen & pelvis w/ contrast 
    proc_cde == "74177" ~ "ct_abdomen_pelvis_w_contrast",
    
    ## MRI abdomen
    proc_cde == "74183" ~ "mri_abdomen",
    
    ## MR enterography
    proc_cde == "74181"|
    proc_cde == "74182" |
    proc_cde == "74183"|
    proc_cde == "72195" |
    proc_cde == "72196"|
    proc_cde == "72197" ~ "mr_enterography",
    
    ## Xray abdomen
    proc_cde == "74018" ~ "xray_abdomen" ))



### create visuals for frequency
# First subset for when labs occurred (no NAs), then group by from_dt
ibs_lab_image %>% filter(lab != "NA") %>% group_by(from_dt, lab, claimno) %>%
  tally %>% mutate(month_day = format(from_dt, "%m-%d"),
                   year = format(from_dt, "%Y"), month = format(from_dt, "%m"))

```

Comparing singular patient to 4 patients 
```{r}
##### IBS/IBD/Crohn's diagnosis for new patients 
####### note: many w/ other potentially interesting diagnoses that don't contain those keywords
dat_4pts %>% filter(grepl('crohn|irritable', Primary_diag, ignore.case = TRUE)) %>% group_by(from_dt, PAT_ID, Primary_diag) %>% tally()


### ED visit info by searching the PROCEDURE_DESC for instances of "emergency department" for that one patient 
dat_4pts %>% filter(PAT_ID == '05imadm9fhf0idl5') %>% filter(grepl("surgical|colectomy", PROCEDURE_DESC, ignore.case = TRUE)) %>%
  group_by(from_dt)


## Get hospitalization lengths
# first subset to the hospitalizations, then group by hospitalization code
# then order by from_dt and tally to see the number of claims on each unique date
# find difference between the first claim date and last claim date + 1 for each unique hospitalization to get total length

# only run before ### to get table w/ unique lengths
# for better graphics, need to mutate into year & month to capture time frame

hosp_duration <- dat_4pts %>% filter(PAT_ID == '05imadm9fhf0idl5') %>% filter(!is.na(conf_num)) %>% 
  group_by(conf_num, from_dt) %>% arrange(from_dt) %>% tally() %>% #only include the distinct() line for small table
  mutate(hosp_length = max(ymd(from_dt)) - min(ymd(from_dt)) + 1) %>% # distinct(conf_num, hosp_length) ####
  distinct(from_dt, .keep_all = TRUE) %>% mutate(month_day = format(from_dt, "%m-%d"),
                                               year = format(from_dt, "%Y"))



ggplot(data = hosp_duration, 
       aes(x = month_day, y = as.numeric(hosp_length), fill = conf_num)) + 
  geom_bar(stat='identity') + labs(title ="Hospitalizations by Month in 2017",
       x = "Month", y = "Hospitalization Length (Days)")


### Now view unique claims for outpatient vs inpatient 
##### inpatient visuals

## pull out inpatient AKA hospitalizations (Have conf_num code) data, remember to filter just for this singular patient
inpatient <- dat_4pts %>% filter(PAT_ID == '05imadm9fhf0idl5') %>% filter(!is.na(conf_num))

# These are the distinct visit dates/distinct claims
inpatient_visits <- inpatient %>%  distinct(from_dt, .keep_all = TRUE) %>% 
  arrange(ymd(.$from_dt)) %>%
  group_by(from_dt, claimno) %>%
  tally


# graph of above for individual visit frequency
## Create plot with unique "from_dt" as x-axis, number of unique visits per date 

ggplot(data = inpatient_visits, aes(x = from_dt, y = n)) +
  geom_bar(stat = "identity", fill = "purple") +
  labs(title ="Unique Inpatient Visit Claims",
       x = "Date", y = "Claims") + ylim(0, 3)

#### outpatient visuals (non-pharmacy)

# get rid of pharmacy claims which have NDC codes

outpatient <- dat_4pts %>% filter(PAT_ID == '05imadm9fhf0idl5') %>% filter(is.na(conf_num)) %>% filter(is.na(ndc))

## Visualize total outpatient claims
#### There are 220 total rows for this, but only 40 unique claims (distinct dates)

# These are the distinct visit dates/distinct claims
outpatient_visits <- outpatient %>%  distinct(from_dt, .keep_all = TRUE) %>% 
  arrange(ymd(.$from_dt)) %>%
  group_by(from_dt, claimno) %>%
  tally


# graph of above for individual visit frequency
## Create plot with unique "from_dt" as x-axis, number of unique visits per date 

ggplot(data = outpatient_visits, aes(x = from_dt, y = n)) +
  geom_bar(stat = "identity", fill = "purple") +
  labs(title ="Unique Outpatient Visit Claims",
       x = "Date", y = "Claims") + ylim(0, 5)
```


