---
title: "figure_frequency"
output: pdf_document
date: '2022-11-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Create just one drug
just_one <- cohort %>% mutate(sulfasalazine = case_when(
    ## Sulfasalazine
    ndc == "00013010101"|
      ndc == "00013010111" |
      ndc == "00013010120"|
      ndc == "00013010201" |
      ndc == "00013010220"|
      ndc == "00591079601" |
      ndc == "00591079605"|
      ndc == "00591079610" |
      ndc == "00603580104"|
      ndc == "00603580121" |
      ndc == "00603580128"|
      ndc == "00603580132" |
      ndc == "00603580321"|
      ndc == "00603580325" |
      ndc == "00677048301"|
      ndc == "00677048305" |
      ndc == "00904115240"|
      ndc == "00904115260" |
      ndc == "38779017604"|
      ndc == "38779017605" |
      ndc == "38779017608"|
      ndc == "38779017609" |
      ndc == "43353049553"|
      ndc == "43353049570" |
      ndc == "43353049580"|
      ndc == "49452752301" |
      ndc == "49452752302"|
      ndc == "51552104405" |
      ndc == "51927104500"|
      ndc == "52544079601" |
      ndc == "52544079605"|
      ndc == "53489014701" |
      ndc == "53489014705"|
      ndc == "54569031303" |
      ndc == "54868112301"|
      ndc == "54868113801" |
      ndc == "54868113900"|
      ndc == "55289017640" |
      ndc == "58016007490"|
      ndc == "59762010401" |
      ndc == "59762010402"|
      ndc == "59762500001" |
      ndc == "59762500002"|
      ndc == "62991270403" |
      ndc == "67544094370"|
      ndc == "67544094380" ~ "sulfasalazine used"))
```


```{r}
## Frequency count of sulfasalazine
just_one %>% group_by(pat_id) %>% filter(sulfasalazine == "sulfasalazine used") %>% count(sulfasalazine) %>% select(pat_id, sulfasalazine)
```
```{r}
## same deal with another drug, different class
 ## Mesalamine
just_one_2 <- cohort %>% mutate(olsalazine_sodium = case_when(
     ndc == "53014072671"|
      ndc == "50474060001" |
      ndc == "00013010501"|
      ndc == "68220016010" |
      ndc == "50474060025"|
      ndc == "00037686010" |
      ndc == "53014072682" ~ "olsalazine_sodium used"))
```

```{r}
## Frequency count of mesalamine
just_one_2 %>% group_by(pat_id) %>% filter(olsalazine_sodium == "olsalazine_sodium used") %>% count(olsalazine_sodium) %>% select(pat_id, olsalazine_sodium)
```


```{r}
#Frequency of patients with total Aminosalicylates
cohort %>% group_by(pat_id) %>% filter(drug_class == "aminosalicylates") %>% count(drug_class) %>% select(pat_id, drug_class)
```

